included:
  - Targets

excluded:
  - Carthage
  - Pods
  - DerivedData
  - Packages

disabled_rules:
  - discarded_notification_center_observer
  - notification_center_detachment
  - orphaned_doc_comment
  - todo
  - line_length
  - nesting
  - trailing_whitespace
  - cyclomatic_complexity
  - function_body_length
  - file_length
  - large_tuple
  - empty_count
  - multiple_closures_with_trailing_closure
  - enum_case_associated_values_count
  - valid_ibinspectable
  - unused_setter_value
  - implicit_getter
  - trailing_newline

opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - colon
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_whitespace_closing_braces
  - yoda_condition
  - unused_capture_list
  - no_print
    
force_cast: warning
force_try: warning

legacy_hashing: error

identifier_name:
  excluded:
    - i
    - id
    - x
    - y
    - z
    - to
    - ad
    - up
    - sn
    - ox
    - my
    - us
    - kr
    - th
    - jp
    - vn
  
private_over_fileprivate:
  validate_extensions: true

vertical_whitespace:
  max_empty_lines: 2

type_body_length:
  - 1000

type_name:
    min_length: 2
    max_length: 100

custom_rules:
  no_print:
    included:
      - "*.swift"
    name: "No Print Statements"
    regex: "print\\("
    message: "Do not use print statements in production code."
    severity: error
